[server]
enableCORS = false

[runner]
# Force Python 3.9
pythonPath = "python3.9"

[theme]
primaryColor="#F63366"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"
